# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Also build PDF format docs
formats:
- pdf

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    post_install:
    # Remove requests-cache, which appears to cause segfaults on RTD workers
    - pip uninstall --yes requests-cache


# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

python:
  install:
  - requirements: doc/requirements.txt
  - method: pip
    path: .
    extra_requirements:
      - docs
