name: Project or paper documentation
description: Provide information about a project or paper for the MESSAGE team.
title: "Document "
labels: ["doc", "paper"]
projects: ["MESSAGEix team"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this documentation issue!

        > [!NOTE]
        > Please complete the issue title with the name of the project or paper you're documenting.
        > Please answer as many of the following points as you can, but no worries if you don't have all the answers right away.
        > These prompts mainly serve as a reminder as to what people may want to know.
        > Feel free to update this issue whenever you have more answers and the time :smiley:
        > Please remember to close this issue once the project is complete.
  - type: textarea
    id: who
    attributes:
      label: Who is responsible?
      description: Please tell us who's responsible for the project. If they have GitHub accounts, please assign them on this issue.
      placeholder: Me, myself, and I.
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What's the goal?
      description: Please tell us what this project is about.
    validations:
      required: true
  - type: textarea
    id: when
    attributes:
      label: When does the project end?
      description: Please tell us the timeframe of this project.
  - type: textarea
    id: where
    attributes:
      label: Where does the project live?
      description: Please tell us where we can find the code and data this project is using.
  - type: textarea
    id: why
    attributes:
      label: Why is this project important?
      description: If you feel so inclined, please provide background information.
  - type: textarea
    id: state
    attributes:
      label: What's the current state of the work?
      description: "Please tell us what has been done already. If the project Scenario's follow a specific naming convention, this is a good place to highlight it :smiley:"
  - type: textarea
    id: more
    attributes:
      label: "For further information, see:"
      description: Please tell us where we can learn more about this project.