# Output configuration for HHI (i.e., where should HHI limits be placed)
hhi_R12_CHN:
  LNG_shipped_exp_chn:
    R12_AFR:
      1
    R12_EEU:
      1
    R12_FSU:
      1
    R12_LAM:
      1
    R12_MEA:
      1
    R12_NAM:
      1
    R12_PAO:
      1
    R12_PAS:
      1
    R12_RCPA:
      1
    R12_SAS:
      1
    R12_WEU:
      1
  gas_piped_exp_chn:
    R12_PAS:
      1
    R12_FSU:
      1

hhi_R12_WEU:
  LNG_shipped_exp_weu:
    R12_AFR:
      1
    R12_CHN:
      1
    R12_EEU:
      1
    R12_FSU:
      1
    R12_LAM:
      1
    R12_MEA:
      1
    R12_NAM:
      1
    R12_PAO:
      1
    R12_PAS:
      1
    R12_RCPA:
      1
    R12_SAS:
      1
  gas_piped_exp_weu:
    R12_AFR:
      1
    R12_EEU:
      1
    R12_FSU:
      1
    R12_MEA:
      1